#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Back credit header in po files
#
# Crowdin will erease all credits in po files. So we have to backup and restore
# them manually. Credits was saved in `credits` folder

# Load environment variables
source environment

# $1 - branch kf5-trunk or kf5-stable
# $2 - language code
# $3 - messages or docmessages
function backup {
    backup_dir=$CREDITS_DIR/$1/$2/$3
    mkdir -p $backup_dir
    po_dir=$ROOT_DIR/$1/$2/$3
    cd $po_dir
    for po_file in $(find -name "*.po"); do
        credit_file=$backup_dir/$(basename $po_file).credit
        > $credit_file # Empty file content
        $COPY_CREDITS $po_file $credit_file
    done
    cd $ROOT_DIR
}

echo "[Backup Credits] start"

for LOCALE in $LOCALES_UNDERSCORE; do
    backup kf5-trunk $LOCALE messages
    backup kf5-trunk $LOCALE docmessages
    backup kf5-stable $LOCALE messages
    backup kf5-stable $LOCALE docmessages
done

echo "[Backup Credits] done"
