#!/bin/bash

# Copyright Guo Yunhe <guoyunhebrave@gmail.com> 2017

# This script will check translation changes before submit.

# Load environment variables
source environment

echo "[SVN Commit] start"

# Commit Krita document sources
cd $ROOT_DIR/kf5-trunk/templates
svn commit -m "Update Krita Document templates"

for locale in $COMMIT_LOCALES_UNDERSCORE; do

    # Commit trunk branch
    echo "[SVN Commit] $locale kf5-trunk"
    cd $ROOT_DIR/kf5-trunk/$locale
    svn commit -m "Crowdin Sync [kf5-trunk] [$locale]"

    # Commit stable branch
    echo "[SVN Commit] $locale kf5-stable"
    cd $ROOT_DIR/kf5-stable/$locale
    svn commit -m "Crowdin Sync [kf5-stable] [$locale]"

done

# Commit Krita document translations
cd $ROOT_DIR/docs-krita-org
git commit -m "Crowdin Sync"
git push

echo "[SVN Commit] done"
