#!/bin/bash

# Copyright Guo Yunhe <guoyunhebrave@gmail.com> 2017

# This script will check translation changes before submit.

# Load environment variables
source environment

echo "[SVN Commit] start"

for locale in $COMMIT_LOCALES_UNDERSCORE; do

    # Commit trunk branch
    echo "[SVN Commit] $locale kf5-trunk"
    cd kf5-trunk/$locale
    svn commit -m "Crowdin Sync [kf5-trunk] [$locale]"

    # Commit stable branch
    echo "[SVN Commit] $locale kf5-stable"
    cd ../../kf5-stable/$locale
    svn commit -m "Crowdin Sync [kf5-stable] [$locale]"

    # Back to project root directory
    cd ../../

done

echo "[SVN Commit] done"
