#!/bin/bash

# Copyright Guo Yunhe <guoyunhebrave@gmail.com> 2017

# This script will check translation changes before submit.

# Diff trunk branch
cd kf5-trunk
svn diff > trunk.diff
if [ -s trunk.diff ] # if diff is not empty
then
    kompare -o trunk.diff
fi

# Back to project root directory
cd ..

# Diff stable branch
cd kf5-stable
svn diff > stable.diff
if [ -s stable.diff ]
then
    kompare -o stable.diff
fi

# End of file
