#!/bin/bash

./update

./backup_credits

cd kf5-trunk
crowdin download -b kf5-trunk | grep " - "> lost.txt

cd ../kf5-stable
crowdin download -b kf5-stable | grep " - "> lost.txt

cd ..

for po in $(find -name "*.po"); do
    msgcat -w 79 -o $po $po
done

./restore_credits

echo "Done!"
