#!/bin/bash

cd kf5-trunk
crowdin download -b kf5-trunk

cd ../kf5-stable
crowdin download -b kf5-stable

cd ..

# Add po head to _qt.po files
for po in $(find -name "*_qt.po"); do
    cp "head" "po_tmp"
    tail -n +4 $po >> "po_tmp"
    mv "po_tmp" $po
done

for po in $(find -name "trojita_common.po"); do
    cp "head" "po_tmp"
    tail -n +4 $po >> "po_tmp"
    mv "po_tmp" $po
done

for po in $(find -name "*.po"); do
    msgcat -w 79 -o $po $po
done

echo "Done!"
