#!/bin/bash

# Copyright Guo Yunhe <guoyunhebrave@gmail.com> 2017

# This script will initialize project and download files from KDE SVN server.
# NOTE: if you run this script again, it would remove old SVN data!

# Remove old data if exists
rm -rf kf5-trunk kf5-stable

PREFIX="svn+ssh://svn@svn.kde.org/home/kde"

svn co $PREFIX/trunk/l10n-kf5 kf5-trunk --depth empty
cd kf5-trunk
svn up templates
svn up zh_CN
cd ..

svn co $PREFIX/branches/stable/l10n-kf5 kf5-stable --depth empty
cd kf5-stable
svn up templates
svn up zh_CN
cd ..

cp crowdin.yaml kf5-trunk
cp crowdin.yaml kf5-stable

# End of file
