#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Initialize project and download files from KDE SVN server.
#
# You need a developer account and ssh key to use this script.
#
# NOTE: if you run this script again, it would remove old SVN data!

# Load environment variables
source environment

# Remove old data if exists
rm -rf kf5-trunk kf5-stable docs-krita-org

# Define URI to SVN server
PREFIX="svn+ssh://svn@svn.kde.org/home/kde"

# Initialize trunk branch
cd $ROOT_DIR
svn co $PREFIX/trunk/l10n-kf5 kf5-trunk --depth empty
cd $ROOT_DIR/kf5-trunk
svn up templates
svn up $LOCALES_UNDERSCORE

# Initialize stable branch
cd $ROOT_DIR
svn co $PREFIX/branches/stable/l10n-kf5 kf5-stable --depth empty
cd $ROOT_DIR/kf5-stable
svn up templates
svn up $LOCALES_UNDERSCORE

# Copy crowdin configuration file to branches
cp $ROOT_DIR/crowdin.yaml $ROOT_DIR/kf5-trunk/
cp $ROOT_DIR/crowdin.yaml $ROOT_DIR/kf5-stable/

# Clone Krita document
cd $ROOT_DIR
git clone git@git.kde.org:websites/docs-krita-org.git

# End of file
