#!/bin/bash

# Create missing po translation files from pot templates
#
# These new po files have some invalid default values in head. You need to use
# "merge" script to initialize content from Crowdin.

generate() {
    for pot in $(find -name "*.pot"); do
        po="../zh_CN/$(echo $pot | sed 's/pot$/po/g')"
        if [ ! -f $po ]; then
            install -m 644 -Dv $pot $po
        fi
    done
}

cd upstream/kf5-trunk/templates
generate

cd ../../kf5-stable/templates
generate

cd ../../../crowdin/kf5-trunk/templates
generate

cd ../../kf5-stable/templates
generate
