#!/bin/bash

# Load environment variables
source environment

root_dir=$(realpath .)
credits_dir=$root_dir/credits
fetch_script=$root_dir/fetch-old-credits.py

function restore {
    work_dir=$credits_dir/$1/$2/$3
    mkdir -p $work_dir
    cd $work_dir
    for po in $(find -name "*.po"); do
        credit_file=$work_dir/$(basename $po).credit
        touch $credit_file
        $fetch_script $credit_file $po
    done
    cd $root_dir
}

for locale in $LOCALES_UNDERSCORE; do
    restore kf5-trunk $locale messages
    restore kf5-trunk $locale docmessages
    restore kf5-stable $locale messages
    restore kf5-stable $locale docmessages
done
