#!/bin/bash

# Load environment variables
source environment

# $1 - branch kf5-trunk or kf5-stable
# $2 - language code
# $3 - messages or docmessages
function restore {
    backup_dir=$CREDITS_DIR/$1/$2/$3
    mkdir -p $backup_dir
    po_dir=$ROOT_DIR/$1/$2/$3
    cd $po_dir
    for po_file in $(find -name "*.po"); do
        credit_file=$backup_dir/$(basename $po_file).credit
        touch $credit_file
        $COPY_CREDITS $credit_file $po_file
    done
    cd $ROOT_DIR
}

echo "[Restore Credits] start"

for locale in $LOCALES_UNDERSCORE; do
    restore kf5-trunk $locale messages
    restore kf5-trunk $locale docmessages
    restore kf5-stable $locale messages
    restore kf5-stable $locale docmessages
done

echo "[Restore Credits] done"
