#!/bin/bash

# Copyright Guo Yunhe <guoyunhebrave@gmail.com> 2017

# Languages
LANGS="zh_CN zh_TW"

# This script will update translation files from KDE SVN server.

cd kf5-trunk
svn revert --depth=infinity .
svn cleanup --remove-unversioned zh_CN
svn up templates
svn up $LANGS

cd ../kf5-stable
svn revert --depth=infinity . # Revert unstaged changes
svn cleanup --remove-unversioned zh_CN # Remove unversioned files
svn up templates
svn up $LANGS

cd ..

# Generate missing po files from pot templates
generate() {
    for pot in $(find -name "*.pot"); do
        for lang in $LANGS; do
            po="../$lang/$(echo $pot | sed 's/pot$/po/g')"
            if [ ! -f $po ]; then
                install -m 644 -Dv $pot $po
                svn add $po -q --parents >/dev/null
            fi
        done
    done
}

cd kf5-trunk/templates
generate

cd ../../kf5-stable/templates
generate

echo "Done!"

# End of file
