#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Update sources and translations from KDE SVN server.

# Load environment variables
source environment

cd kf5-trunk
svn revert --depth=infinity .
svn cleanup --remove-unversioned zh_CN
svn up templates
svn up $LOCALES_UNDERSCORE

cd ../kf5-stable
svn revert --depth=infinity . # Revert unstaged changes
svn cleanup --remove-unversioned zh_CN # Remove unversioned files
svn up templates
svn up $LOCALES_UNDERSCORE

cd ..

# Generate missing po files from pot templates
generate() {
    for pot in $(find -name "*.pot"); do
        for locale in $LOCALES_UNDERSCORE; do
            po="../$locale/$(echo $pot | sed 's/pot$/po/g')"
            if [ ! -f $po ]; then
                install -m 644 -Dv $pot $po
                svn add $po -q --parents >/dev/null
            fi
        done
    done
}

cd kf5-trunk/templates
generate

cd ../../kf5-stable/templates
generate

# End of file
