#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Upload translations to Crowdin
#
# This script is only used for new language set up and it will be never used
# again once the language has been initialized.
#
# Usage:
#
#   ./upload_translations [Language Code]
#
# Language Code is in zh-CN, en-US format, not zh_CN, en_US format.
# Same translation won't be uploaded twice.

echo "[Upload Translations] start"

# Upload trunk
cd kf5-trunk
crowdin upload translations -b kf5-trunk -l $1 --import-eq-suggestions

cd ..

# Upload stable
cd kf5-stable
crowdin upload translations -b kf5-stable -l $1 --import-eq-suggestions

echo "[Upload Translations] done"
