#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Upload local source pots to Crowdin

./update

cd kf5-trunk
crowdin upload sources -b kf5-trunk

cd ../kf5-stable
crowdin upload sources -b kf5-stable

# End of file
