#!/bin/bash

# Author: Guo Yunhe <i@guoyunhe.me>
# Updated: 2019-01-27

# Upload translations to Crowdin
#
# This script is only used for new language set up and it will be never used
# again once the language has been initialized.
#
# Usage:
#
#   ./upload_translations [Language Code]
#
# Language Code is in zh-CN, en-US format, not zh_CN, en_US format.
# Same translation won't be uploaded twice.

# Load environment variables
source environment

echo "[Upload Translations] start"

# Always update stable first to avoid losing translations or approvals
cd $ROOT_DIR/kf5-stable
if [ $# -eq 0 ]
then
    crowdin upload translations -b kf5-stable --import-eq-suggestions
else
    crowdin upload translations -b kf5-stable -l $1 --import-eq-suggestions
fi

cd $ROOT_DIR/kf5-trunk
if [ $# -eq 0 ]
then
    crowdin upload translations -b kf5-trunk --import-eq-suggestions
else
    crowdin upload translations -b kf5-trunk -l $1 --import-eq-suggestions
fi

echo "[Upload Translations] done"
