#!/bin/bash

# Author: Guo Yunhe <guoyunhebrave@gmail.com>
# Updated: 2018-04-05

# Upload local source pots to Crowdin

# Load environment variables
source environment

./update

echo "[Upload Sources] start"

cd $ROOT_DIR/kf5-trunk
crowdin upload sources -b kf5-trunk

cd $ROOT_DIR/kf5-stable
crowdin upload sources -b kf5-stable

echo "[Upload Sources] done"
